### ISSUE TITLE
Installation Lab

### ISSUE THREAD

**Issue by rakesh18t** [rakesh18t/SEBC#1]

**Comment by mfernest** [comment]
Please use labels, assign a milestone and who is working on this right now (you).

**Comment by rakesh18t** [comment]
AWS-EC2 - 5x Instances created. Availability Zone - eu-west-1a
![aws-ec2 - instances](https://cloud.githubusercontent.com/assets/23405371/20270545/26e98678-aa90-11e6-807d-58f819f4292b.PNG)
