### ISSUE TITLE
Test HDFS

### ISSUE THREAD

**Issue by rakesh18t** [rakesh18t/SEBC#17]

**Comment by mfernest** [comment]
* `4_teragen.md` - the requirement was to run a teragen job as user `raffles`. That will not work unless the ownership and permissions are set correctly for `/user/raffles`. Running the job as user `hdfs` and placing the output in `/user/raffles` is not sufficient. 
* The full output of the job wasn't submitted. 
* The block count, to show the full teragen created the required amount of data, also wasn't submitted.

Incomplete.
