### ISSUE TITLE
Please follow Readme.md instructions and _assign_ labels for the issues

### ISSUE THREAD

**Issue by jqnik** [rakesh18t/SEBC#2]

**Comment by jqnik** [comment]
sorry, you've got the labels. I meant assign :)

**Comment by rakesh18t** [comment]
AWS-EC2 - 5x Instances created. Availability Zone - eu-west-1a
![aws-ec2 - instances](https://cloud.githubusercontent.com/assets/23405371/20270368/729c1ca8-aa8f-11e6-80d2-4aabd7a86379.PNG)

**Comment by jqnik** [comment]
You should probably give a name to each of these. did you tag these with your user name, or have any other means of identifying them later on (assuming there are much more instances in this list)

**Comment by rakesh18t** [comment]
I have tagged them relevant to the roles that i will setup. Include the .png in the Installation Folder
